packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Build & Dev Tools
  "@eslint/js": ^9.39.2
  "@tailwindcss/vite": ^4.1.18
  "@vitejs/plugin-react": ^5.1.3
  eslint: ^9.39.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  globals: ^16.5.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vite: ^7.3.1

  # React & Core
  react: ^19.2.3
  react-dom: ^19.2.3
  react-router-dom: ^7.12.0
  tailwindcss: ^4.1.18
  zustand: 5.0.10

  # Form & Validation
  "@hookform/resolvers": ^5.2.2
  react-hook-form: ^7.71.0
  zod: ^4.3.5

  # Charts
  d3: ^7.9.0
  recharts: ^3.7.0

  # Utilities
  "@types/lodash": ^4.17.21
  "@types/node": ^25.0.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  lodash: ^4.17.21

  # Testing
  vitest: ^3.1.3
  "@vitest/coverage-v8": ^3.1.3
  "@testing-library/react": ^16.3.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/user-event": ^14.6.1
  jsdom: ^26.1.0

onlyBuiltDependencies:
  - esbuild
