packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.2
  '@hookform/resolvers': ^5.2.2
  '@react-three/drei': ^10.7.7
  '@react-three/fiber': ^9.4.2
  '@storybook/addon-essentials': ^8.6.14
  '@storybook/addon-interactions': ^8.6.14
  '@storybook/addon-links': ^8.6.14
  '@storybook/blocks': ^8.6.14
  '@storybook/react': ^8.6.14
  '@storybook/react-vite': ^8.6.14
  '@storybook/test': ^8.6.14
  '@tailwindcss/vite': ^4.1.18
  '@types/lodash': ^4.17.21
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/three': 0.182.0
  '@vitejs/plugin-react': ^5.1.2
  eslint: ^9.39.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  globals: ^16.5.0
  lodash: ^4.17.21
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: ^7.71.0
  react-router-dom: ^7.12.0
  storybook: ^8.6.14
  tailwindcss: ^4.1.18
  three: 0.182.0
  three-stdlib: ^2.36.1
  typescript: ^5.9.3
  typescript-eslint: ^8.53.0
  vite: ^7.3.1
  zod: ^4.3.5
  zustand: 5.0.10

onlyBuiltDependencies:
  - esbuild
