packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.2
  '@hookform/resolvers': ^5.2.2
  '@tailwindcss/vite': ^4.1.18
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/lodash': ^4.17.21
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.3
  '@vitest/coverage-v8': ^3.1.3
  d3: ^7.9.0
  eslint: ^9.39.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  globals: ^16.5.0
  jsdom: ^26.1.0
  lodash: ^4.17.21
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: ^7.71.0
  react-router-dom: ^7.12.0
  recharts: ^3.7.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vite: ^7.3.1
  vitest: ^3.1.3
  zod: ^4.3.5
  zustand: 5.0.10
  cron-parser: ^5.5.0

onlyBuiltDependencies:
  - esbuild
